### ISSUE TITLE
Translation to Korean

### ISSUE THREAD

**Issue by yohanhyunsungyi** [angelolloqui/SwiftKotlin#54]
Hey there! 
I am a Swift developer who is studying Android development. 
As a mobile application developer, I was impressed with your work.
I would like to introduce these good works to Koreans.
Is there any chance that I can help translate Readme.md to Korean?

**Comment by angelolloqui** [comment]
Hi @YohanHyunsungYi 

Contributors are always welcomed, no matter what or how they contribute. My only question is what are your plans on long term? what will happen when I update the Readme (which I do every now and then)? will you translate it again or is this a one time work? 

I would rather prefer not to have translations than having translations which are outdated, so that is a very important point to me, some commitment with future updates.

Anyway, if you feel OK updating the readme when we change the English one, and you think it will help other Korean devs to use it I am open to it. Just let me know and open a PR with a new Readme with the `.kr` suffix and I will merge it.

Thanks!

**Comment by angelolloqui** [comment]
Closing this as there was no response for 2 months
